### ISSUE TITLE
Context deadline exceeded when running Movr 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/movr#49]
After running:

`docker run -it --rm natestewart/movr --url "postgres://root@104.198.0.224:26257/movr?sslmode=disable" load --enable-geo-partitioning`

I see:

sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) server closed the connection unexpectedly
    This probably means the server terminated abnormally
    before or while processing the request.
 (Background on this error at: http://sqlalche.me/e/e3q8)

I checked the logs and see lots of `context deadline exceeded`:

E181008 18:09:46.097805 44085 server/admin.go:173  admi-show-db: context deadline exceeded
E181008 18:09:46.175336 44088 server/admin.go:212  admin-show-grants: context deadline exceeded
E181008 18:09:46.189935 44041 server/admin.go:212  admin-show-grants: context deadline exceeded
E181008 18:09:46.200893 44044 server/admin.go:212  admin-show-grants: context deadline exceeded
E181008 18:09:46.210733 44074 server/admin.go:212  admin-show-grants: context deadline exceeded

**Comment by nstewart** [comment]
Closing this as it hasn't reproed since 2.0.5
