### ISSUE TITLE
Create example that requires location aware indexing

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/movr#55]
https://github.com/cockroachdb/cockroach/issues/31955

**Comment by jseldess** [comment]
For reference, the perf tuning tutorial using the [movr schema](https://www.cockroachlabs.com/docs/stable/performance-tuning.html#schema) and leverages [table and index partitions](https://www.cockroachlabs.com/docs/stable/performance-tuning.html#step-13-partition-data-by-city) for global performance optimization.

**Comment by nstewart** [comment]
Via @danhhz - I'm going to explore a discount code -> discount details (description, expiration date, etc) use case

**Comment by nstewart** [comment]
This was closed with https://github.com/cockroachdb/movr/pull/78
