### ISSUE TITLE
Document how to use MovR with `workload` and `demo`

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/movr#90]
`./cockroach workload fixtures import movr` works now. You can also `cockroach demo movr`

**Comment by ericharmeling** [comment]
@nstewart I'd love to help out with this as part of this initiative: https://github.com/cockroachdb/docs/issues/2849#issuecomment-509316569

**Comment by nstewart** [comment]
It’s all yours :)

Nate Stewart
VP of Product, Cockroach Labs
Check out our blog: www.cockroachlabs.com/blog/ ( http://www.cockroachlabs.com/blog/ )

**Comment by ericharmeling** [comment]
Awesome! :)
