### ISSUE TITLE
Build a frontend for MovR

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/movr#93]

**Comment by ericharmeling** [comment]
https://github.com/ericharmeling/movr/tree/web-server

**Comment by jseldess** [comment]
@nstewart, @ericharmeling, can we close this one? We don't have a front-end for the loadgen version, but we do for the full-stack multi-region version that Eric build as well as the Cockroach U versions.

**Comment by nstewart** [comment]
fine with me
